
#ifndef TMB_OBJECTIVE_FUNCTIONCPP_EXPORT_H
#define TMB_OBJECTIVE_FUNCTIONCPP_EXPORT_H

#ifdef TMB_OBJECTIVE_FUNCTIONCPP_STATIC_DEFINE
#  define TMB_OBJECTIVE_FUNCTIONCPP_EXPORT
#  define TMB_OBJECTIVE_FUNCTIONCPP_NO_EXPORT
#else
#  ifndef TMB_OBJECTIVE_FUNCTIONCPP_EXPORT
#    ifdef tmb_objective_functioncpp_EXPORTS
        /* We are building this library */
#      define TMB_OBJECTIVE_FUNCTIONCPP_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define TMB_OBJECTIVE_FUNCTIONCPP_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef TMB_OBJECTIVE_FUNCTIONCPP_NO_EXPORT
#    define TMB_OBJECTIVE_FUNCTIONCPP_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef TMB_OBJECTIVE_FUNCTIONCPP_DEPRECATED
#  define TMB_OBJECTIVE_FUNCTIONCPP_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef TMB_OBJECTIVE_FUNCTIONCPP_DEPRECATED_EXPORT
#  define TMB_OBJECTIVE_FUNCTIONCPP_DEPRECATED_EXPORT TMB_OBJECTIVE_FUNCTIONCPP_EXPORT TMB_OBJECTIVE_FUNCTIONCPP_DEPRECATED
#endif

#ifndef TMB_OBJECTIVE_FUNCTIONCPP_DEPRECATED_NO_EXPORT
#  define TMB_OBJECTIVE_FUNCTIONCPP_DEPRECATED_NO_EXPORT TMB_OBJECTIVE_FUNCTIONCPP_NO_EXPORT TMB_OBJECTIVE_FUNCTIONCPP_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef TMB_OBJECTIVE_FUNCTIONCPP_NO_DEPRECATED
#    define TMB_OBJECTIVE_FUNCTIONCPP_NO_DEPRECATED
#  endif
#endif

#endif /* TMB_OBJECTIVE_FUNCTIONCPP_EXPORT_H */
